version: '3'

services:
  hugo:
    build: .
    volumes:
      - ".:/src/"
      - "./output/:/output"
    environment:
      - HUGO_REFRESH_TIME=3600
      - HUGO_THEME=docsy
      - HUGO_BASEURL=
      - HUGO_WATCH=true
    restart: always

  web:
    image: jojomi/nginx-static
    volumes:
      - ./output:/var/www
    environment:
      - VIRTUAL_HOST=seedfinding.com
    ports:
      - 127.0.0.1:5005:80
    restart: always
